spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: yuxuan666
    driverClassName: com.mysql.cj.jdbc.Driver

# MyBatis
mybatis:
  # 指定搜索包名
  typeAliasesPackage: com.xuan.dao.domain
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  #classpath:只能加载找到的第一个资源文件    classpath*:能加载多个路径下的资源文件
  mapperLocations: classpath*:mapper/*.xml
